Add --always
palantir/gradle-git-version pull request #53
Opened 2017-04-04 08:13 UTC by wtanaka

2017-04-04 08:13 UTC, palantirtech commented
Thanks for your interest in [palantir/gradle-git-version](https://github.com/palantir/gradle-git-version), @wtanaka! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2017-04-04 08:38 UTC, wtanaka commented
@uschi2000 @markelliot

2017-04-05 15:52 UTC, uschi2000 requested changes
I'm fine with this, modulo two nitpicks.

2017-04-05 15:52 UTC, uschi2000 commented on src/test/groovy/com/palantir/gradle/gitversion/GitVersionPluginTests.groovy
> +        String expected = git.getRepository().getRef("HEAD").getObjectId().abbreviate(VERSION_ABBR_LENGTH).name()
the test method name is outdated.

2017-04-05 15:52 UTC, uschi2000 commented on src/test/groovy/com/palantir/gradle/gitversion/GitVersionPluginTests.groovy
> +        String expected = git.getRepository().getRef("HEAD").getObjectId().abbreviate(VERSION_ABBR_LENGTH).name()
can you turn this into a method, and also keep the VERSION_ABBR_LENGTH variable local to that method?

2017-04-08 07:03 UTC, wtanaka commented on src/test/groovy/com/palantir/gradle/gitversion/GitVersionPluginTests.groovy
> +        String expected = git.getRepository().getRef("HEAD").getObjectId().abbreviate(VERSION_ABBR_LENGTH).name()
updated

2017-04-08 07:04 UTC, wtanaka commented on src/test/groovy/com/palantir/gradle/gitversion/GitVersionPluginTests.groovy
> +        String expected = git.getRepository().getRef("HEAD").getObjectId().abbreviate(VERSION_ABBR_LENGTH).name()
done

2017-04-08 15:28 UTC, wtanaka commented
@uschi2000 updated

2017-04-08 15:35 UTC, uschi2000 approved these changes

2017-04-08 15:36 UTC, merged