Add VersionDetails#isCleanTag
palantir/gradle-git-version pull request #58
Opened 2017-05-10 13:46 UTC by iamdanfox

2017-05-10 13:53 UTC, iamdanfox commented on src/test/groovy/com/palantir/gradle/gitversion/GitVersionPluginTests.groovy
> +    def 'version details not null when no tags are present' () {
Note: this is a behaviour change

2017-05-12 16:15 UTC, uschi2000 requested changes

2017-05-12 16:15 UTC, uschi2000 commented on src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy
> +            return null
not a big fan of the nulls everywhere. isn't reasonable to just fail instead of returning nulls (both here and below)?

2017-05-12 16:40 UTC, iamdanfox commented on src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy
> +            return null
I'm matching behaviour here - when these commands fail, we output the string 'unspecified'.

2017-05-12 16:48 UTC, uschi2000 commented
OK

On Fri, May 12, 2017, 6:40 PM iamdanfox <notifications@github.com> wrote:

> *@iamdanfox* commented on this pull request.
> ------------------------------
>
> In src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy
> <https://github.com/palantir/gradle-git-version/pull/58#discussion_r116273594>
> :
>
> >          } catch (Throwable t) {
> -            return UNSPECIFIED_VERSION
> +            return null
>
> I'm matching behaviour here - when these commands fail, we output the
> string 'unspecified'.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/palantir/gradle-git-version/pull/58#discussion_r116273594>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGOdwcun-eme0X1DXdULEJL5VNMFvfa4ks5r5ItjgaJpZM4NWr_h>
> .
>

2017-05-15 14:06 UTC, iamdanfox commented
@uschi2000 if you're happy with this, can you hit merge? I don't have any permissions on this repo.

2017-05-15 15:54 UTC, uschi2000 approved these changes

2017-05-15 15:54 UTC, merged